//
//  SettingsView.swift
//  Epilogue
//
//  Created on 2026-01-26.
//  Copyright © 2026 Epilogue. All rights reserved.
//

import SwiftUI
import Domain
import GhostwriterClient
import UniformTypeIdentifiers

struct SettingsView: View {
    @Environment(\.settingsRepository) private var settingsRepository
    @EnvironmentObject private var ghostwriterCoordinator: GhostwriterSyncCoordinator
    @EnvironmentObject private var localDigestService: LocalDigestService
    private let ghostwriterSettingsEnabled = false

    @State private var apiKey = ""
    @State private var showApiKey = false
    @State private var enabledPeriods: Set<DigestPeriod> = [.morning]
    @State private var minWordCount = 300
    @State private var showNotifications = true
    @State private var ghostwriterEnabled = false
    @State private var isGenerating = false
    @State private var apiKeySaved = false
    @State private var ghostwriterStatus: DigestStatusResponse?
    @State private var ghostwriterStatusError: String?
    @State private var ghostwriterStatusTask: Task<Void, Never>?
    @State private var exportEnabled = false
    @State private var exportFolderURL: URL?
    @State private var showExportPicker = false
    @State private var exportError: String?
    @State private var serverSchedule: GhostwriterSchedule?

    var body: some View {
        NavigationStack {
            Form {
                if ghostwriterSettingsEnabled {
                    // MARK: - Ghostwriter Sync
                    Section {
                        NavigationLink {
                            GhostwriterSettingsView(settingsRepository: settingsRepository)
                                .environmentObject(ghostwriterCoordinator)
                        } label: {
                            HStack {
                                Label("Ghostwriter", systemImage: "cloud.fill")
                                Spacer()
                                if ghostwriterEnabled {
                                    Text("Enabled")
                                        .foregroundColor(.secondary)
                                        .font(.caption)
                                }
                                if ghostwriterCoordinator.isSyncing {
                                    ProgressView()
                                        .scaleEffect(0.8)
                                } else if ghostwriterCoordinator.lastSyncError != nil {
                                    Image(systemName: "exclamationmark.triangle.fill")
                                        .foregroundColor(.orange)
                                }
                            }
                        }
                    } footer: {
                        if ghostwriterEnabled {
                            Text("Digests will be generated by the Ghostwriter server. Local generation is disabled.")
                        } else if let lastSync = ghostwriterCoordinator.lastSyncTime {
                            Text("Last sync: \(lastSync.formatted(date: .abbreviated, time: .shortened))")
                        }
                    }
                }

                // MARK: - API Configuration (only for local generation)
                if !ghostwriterEnabled {
                    Section("OpenAI API Key") {
                        HStack {
                            if showApiKey {
                                TextField("API Key", text: $apiKey)
                                    .textInputAutocapitalization(.never)
                                    .autocorrectionDisabled()
                            } else {
                                SecureField("API Key", text: $apiKey)
                                    .textInputAutocapitalization(.never)
                                    .autocorrectionDisabled()
                            }
                            Button {
                                showApiKey.toggle()
                            } label: {
                                Image(systemName: showApiKey ? "eye.slash" : "eye")
                                    .foregroundStyle(.secondary)
                            }
                            .buttonStyle(.borderless)
                        }
                        HStack {
                            Text("Required for Briefing mode. Get your key at platform.openai.com")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                            Spacer()
                            Button("Save") {
                                Task { await saveApiKey() }
                            }
                            .buttonStyle(.borderedProminent)
                            .controlSize(.small)
                        }
                    }
                    .alert("API Key Saved", isPresented: $apiKeySaved) {
                        Button("OK", role: .cancel) { }
                    }
                }

                // MARK: - Schedule
                Section {
                    ForEach(DigestPeriod.allCases, id: \.self) { period in
                        Toggle(isOn: Binding(
                            get: { enabledPeriods.contains(period) },
                            set: { enabled in
                                Task { await togglePeriod(period, enabled: enabled) }
                            }
                        )) {
                            HStack {
                                Image(systemName: period.iconName)
                                    .foregroundColor(periodColor(period))
                                    .frame(width: 24)
                                Text(period.displayName)
                                Spacer()
                                Text(displayTime(for: period))
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                } header: {
                    Text("Daily Schedule")
                } footer: {
                    if enabledPeriods.isEmpty {
                        Text("Select at least one time period")
                            .foregroundColor(.red)
                    } else if ghostwriterEnabled {
                        Text("Ghostwriter server will generate digests at selected times")
                    } else {
                        Text("EPUB will be generated locally at selected times")
                    }
                }

                // MARK: - Content Filters
                Section("Content Filters") {
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text("Minimum word count")
                            Spacer()
                            Text(minWordCount == 0 ? "Off" : "\(minWordCount)")
                                .foregroundStyle(.secondary)
                        }
                        Slider(
                            value: Binding(
                                get: { Double(minWordCount) },
                                set: { newValue in
                                    let count = Int(newValue)
                                    minWordCount = count
                                    Task { await updateMinWordCount(count) }
                                }
                            ),
                            in: 0...1000,
                            step: 100
                        )
                    }
                    Text("Skip articles shorter than this (0 = include all)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                // MARK: - Export Directory
                Section("Export Directory") {
                    Toggle(isOn: Binding(
                        get: { exportEnabled },
                        set: { enabled in
                            Task { await setExportEnabled(enabled) }
                        }
                    )) {
                        VStack(alignment: .leading, spacing: 4) {
                            Text("Export to custom folder")
                            if let url = exportFolderURL {
                                Text(url.lastPathComponent)
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                        }
                    }
                    .disabled(exportFolderURL == nil)

                    HStack {
                        Button(exportFolderURL == nil ? "Select Folder" : "Change") {
                            showExportPicker = true
                        }
                        if exportFolderURL != nil {
                            Button("Clear") {
                                Task { await clearExportFolder() }
                            }
                            .foregroundColor(.red)
                        }
                    }

                    Text("EPUBs will be copied to this folder (e.g., KOReader)")
                        .font(.caption)
                        .foregroundStyle(.secondary)

                    if let error = exportError {
                        Text(error)
                            .font(.caption)
                            .foregroundStyle(.red)
                    }
                }

                // MARK: - Notifications
                Section("Notifications") {
                    Toggle("Show Digest Completion", isOn: $showNotifications)
                }

                // MARK: - Sync (only when Ghostwriter enabled)
                if ghostwriterEnabled {
                    Section {
                        Button {
                            Task { await syncNow() }
                        } label: {
                            HStack {
                                Label("Sync Now", systemImage: "arrow.triangle.2.circlepath")
                                Spacer()
                                if ghostwriterCoordinator.isSyncing {
                                    ProgressView()
                                }
                            }
                        }
                        .disabled(ghostwriterCoordinator.isSyncing)
                    } footer: {
                        if let error = ghostwriterCoordinator.lastSyncError {
                            Text("Sync error: \(error.localizedDescription)")
                                .foregroundColor(.red)
                        } else if let lastSync = ghostwriterCoordinator.lastSyncTime {
                            Text("Last sync: \(lastSync.formatted(date: .abbreviated, time: .shortened))")
                        }
                    }
                }

                // MARK: - Manual Generation
                Section {
                    Button {
                        Task { await generateDigestNow() }
                    } label: {
                        HStack {
                            Spacer()
                            if isGenerating || localDigestService.isGenerating {
                                ProgressView()
                                    .padding(.trailing, 8)
                                Text(localDigestService.generationStatus.isEmpty ? "Generating..." : localDigestService.generationStatus)
                            } else {
                                Text("Generate Digest Now")
                            }
                            Spacer()
                        }
                    }
                    .disabled(isGenerating || localDigestService.isGenerating || ghostwriterCoordinator.isSyncing)

                    if ghostwriterEnabled {
                        if let status = ghostwriterStatus {
                            VStack(alignment: .leading, spacing: 6) {
                                Text("Stage: \(status.stage ?? "starting")")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)

                                ProgressView(value: status.progress.progressPercentage)

                                Text("Feeds: \(status.progress.feedsFetched)/\(status.progress.totalFeeds) | " +
                                     "Articles: \(status.progress.articlesEnriched)/\(status.progress.totalArticles)")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                            .padding(.top, 6)
                        }

                        if let error = ghostwriterStatusError {
                            Text("Error: \(error)")
                                .font(.caption)
                                .foregroundStyle(.red)
                        }
                    }
                } footer: {
                    if ghostwriterEnabled {
                        Text("Will trigger digest generation on the Ghostwriter server")
                    } else if let error = localDigestService.generationError {
                        Text("Last error: \(error.localizedDescription)")
                            .foregroundColor(.red)
                    } else if let digest = localDigestService.lastGeneratedDigest {
                        Text("Last digest: \(digest.articleCount) articles")
                    } else {
                        Text("Will generate a digest locally on this device")
                    }
                }
            }
            .navigationTitle("Settings")
            .task {
                await loadSettings()
            }
            .onChange(of: ghostwriterCoordinator.isSyncing) { _, isSyncing in
                // Reload settings after sync completes to pick up server values
                if !isSyncing {
                    Task { await loadSettings() }
                }
            }
            .fileImporter(
                isPresented: $showExportPicker,
                allowedContentTypes: [.folder],
                allowsMultipleSelection: false
            ) { result in
                switch result {
                case .success(let urls):
                    if let url = urls.first {
                        Task { await setExportFolder(url) }
                    }
                case .failure(let error):
                    exportError = error.localizedDescription
                }
            }
        }
    }

    // MARK: - Helper Methods

    private func periodColor(_ period: DigestPeriod) -> Color {
        switch period {
        case .morning: return .orange
        case .noon: return .yellow
        case .evening: return .purple
        }
    }

    private func loadSettings() async {
        do {
            apiKey = try await settingsRepository.getOpenAIKey() ?? ""
            enabledPeriods = try await settingsRepository.getEnabledPeriods()
            minWordCount = try await settingsRepository.getMinWordCount()
            showNotifications = try await settingsRepository.shouldShowNotifications()
            ghostwriterEnabled = ghostwriterSettingsEnabled && (try await settingsRepository.isGhostwriterEnabled())
            exportEnabled = try await settingsRepository.getCustomExportEnabled()
            serverSchedule = ghostwriterSettingsEnabled ? (try await settingsRepository.getGhostwriterSchedule()) : nil
            if let bookmark = try await settingsRepository.getCustomExportBookmark() {
                exportFolderURL = try resolveExportBookmark(bookmark)
            }
        } catch {
            // Use defaults on error
        }
    }

    /// Returns the display time for a period from server schedule, falling back to defaults
    private func displayTime(for period: DigestPeriod) -> String {
        guard let schedule = serverSchedule else {
            return period.displayTime
        }
        switch period {
        case .morning: return schedule.formattedMorning()
        case .noon: return schedule.formattedNoon()
        case .evening: return schedule.formattedEvening()
        }
    }

    private func togglePeriod(_ period: DigestPeriod, enabled: Bool) async {
        do {
            try await settingsRepository.togglePeriod(period, enabled: enabled)
            enabledPeriods = try await settingsRepository.getEnabledPeriods()

            if ghostwriterEnabled {
                try await ghostwriterCoordinator.updateSchedule(period: period, enabled: enabled)
            }
        } catch {
            // Revert on error
        }
    }

    private func updateMinWordCount(_ count: Int) async {
        do {
            try await settingsRepository.setMinWordCount(count)
            if ghostwriterEnabled {
                try await ghostwriterCoordinator.pushMinWordCount(count)
            }
        } catch {
            // Ignore for now; UI keeps local value.
        }
    }

    private func saveApiKey() async {
        do {
            try await settingsRepository.setOpenAIKey(apiKey)
            apiKeySaved = true
        } catch {
            // Handle error
        }
    }

    private func syncNow() async {
        await ghostwriterCoordinator.performFullSync()
    }

    private func generateDigestNow() async {
        if ghostwriterEnabled {
            // Trigger on Ghostwriter server
            isGenerating = true
            defer { isGenerating = false }
            do {
                ghostwriterStatusTask?.cancel()
                ghostwriterStatus = nil
                ghostwriterStatusError = nil

                let response = try await ghostwriterCoordinator.triggerDigest(period: "manual")
                guard let digestId = response.id else {
                    ghostwriterStatusError = "No digest ID returned"
                    return
                }

                ghostwriterStatusTask = Task {
                    await pollGhostwriterStatus(digestId: digestId)
                }
            } catch {
                ghostwriterStatusError = error.localizedDescription
            }
        } else {
            // Local generation
            await localDigestService.generateDigest()
        }
    }

    private func setExportFolder(_ url: URL) async {
        do {
            let creationOptions: URL.BookmarkCreationOptions = {
#if os(macOS)
                return [.withSecurityScope]
#else
                return []
#endif
            }()
            let bookmark = try url.bookmarkData(options: creationOptions)
            try await settingsRepository.setCustomExportBookmark(bookmark)
            try await settingsRepository.setCustomExportEnabled(true)
            exportFolderURL = url
            exportEnabled = true
            exportError = nil
        } catch {
            exportError = error.localizedDescription
        }
    }

    private func clearExportFolder() async {
        do {
            try await settingsRepository.setCustomExportBookmark(nil)
            try await settingsRepository.setCustomExportEnabled(false)
            exportFolderURL = nil
            exportEnabled = false
            exportError = nil
        } catch {
            exportError = error.localizedDescription
        }
    }

    private func setExportEnabled(_ enabled: Bool) async {
        do {
            try await settingsRepository.setCustomExportEnabled(enabled)
            exportEnabled = enabled
        } catch {
            exportError = error.localizedDescription
        }
    }

    private func resolveExportBookmark(_ bookmark: Data) throws -> URL {
        var isStale = false
        let resolveOptions: URL.BookmarkResolutionOptions = {
#if os(macOS)
            return [.withSecurityScope]
#else
            return []
#endif
        }()
        let url = try URL(
            resolvingBookmarkData: bookmark,
            options: resolveOptions,
            relativeTo: nil,
            bookmarkDataIsStale: &isStale
        )
        if isStale {
            let creationOptions: URL.BookmarkCreationOptions = {
#if os(macOS)
                return [.withSecurityScope]
#else
                return []
#endif
            }()
            let refreshed = try url.bookmarkData(options: creationOptions)
            Task { try? await settingsRepository.setCustomExportBookmark(refreshed) }
        }
        return url
    }

    private func pollGhostwriterStatus(digestId: String) async {
        while !Task.isCancelled {
            do {
                let status = try await ghostwriterCoordinator.getDigestStatus(digestId: digestId)
                ghostwriterStatus = status

                if status.isComplete {
                    break
                }
            } catch {
                ghostwriterStatusError = error.localizedDescription
                break
            }

            try? await Task.sleep(nanoseconds: 1_500_000_000)
        }
    }
}
