//
//  SettingsView.swift
//  Epilogue
//
//  Created on 2026-01-26.
//  Copyright © 2026 Epilogue. All rights reserved.
//

import SwiftUI
import Domain

struct SettingsView: View {
    @Environment(\.settingsRepository) private var settingsRepository
    @EnvironmentObject private var ghostwriterCoordinator: GhostwriterSyncCoordinator

    @State private var apiKey = ""
    @State private var enabledPeriods: Set<DigestPeriod> = [.morning]
    @State private var minWordCount = 300
    @State private var showNotifications = true
    @State private var ghostwriterEnabled = false
    @State private var isGenerating = false

    var body: some View {
        NavigationStack {
            Form {
                // MARK: - Ghostwriter Sync
                Section {
                    NavigationLink {
                        GhostwriterSettingsView(settingsRepository: settingsRepository)
                            .environmentObject(ghostwriterCoordinator)
                    } label: {
                        HStack {
                            Label("Ghostwriter", systemImage: "cloud.fill")
                            Spacer()
                            if ghostwriterEnabled {
                                Text("Enabled")
                                    .foregroundColor(.secondary)
                                    .font(.caption)
                            }
                            if ghostwriterCoordinator.isSyncing {
                                ProgressView()
                                    .scaleEffect(0.8)
                            } else if ghostwriterCoordinator.lastSyncError != nil {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundColor(.orange)
                            }
                        }
                    }
                } footer: {
                    if ghostwriterEnabled {
                        Text("Digests will be generated by the Ghostwriter server. Local generation is disabled.")
                    } else if let lastSync = ghostwriterCoordinator.lastSyncTime {
                        Text("Last sync: \(lastSync.formatted(date: .abbreviated, time: .shortened))")
                    }
                }

                // MARK: - API Configuration (only for local generation)
                if !ghostwriterEnabled {
                    Section("OpenAI API Key") {
                        SecureField("API Key", text: $apiKey)
                            .textInputAutocapitalization(.never)
                            .autocorrectionDisabled()
                        Text("Required for Briefing mode. Get your key at platform.openai.com")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }
                }

                // MARK: - Schedule
                Section {
                    ForEach(DigestPeriod.allCases, id: \.self) { period in
                        Toggle(isOn: Binding(
                            get: { enabledPeriods.contains(period) },
                            set: { enabled in
                                Task { await togglePeriod(period, enabled: enabled) }
                            }
                        )) {
                            HStack {
                                Image(systemName: period.iconName)
                                    .foregroundColor(periodColor(period))
                                    .frame(width: 24)
                                Text(period.displayName)
                                Spacer()
                                Text(period.displayTime)
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                } header: {
                    Text("Daily Schedule")
                } footer: {
                    if enabledPeriods.isEmpty {
                        Text("Select at least one time period")
                            .foregroundColor(.red)
                    } else if ghostwriterEnabled {
                        Text("Ghostwriter server will generate digests at selected times")
                    } else {
                        Text("EPUB will be generated locally at selected times")
                    }
                }

                // MARK: - Content Filters
                Section("Content Filters") {
                    Stepper("Min Word Count: \(minWordCount)", value: $minWordCount, in: 0...1000, step: 50)
                    Text("Articles shorter than this will be filtered out in Fidelity mode")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                // MARK: - Notifications
                Section("Notifications") {
                    Toggle("Show Digest Completion", isOn: $showNotifications)
                }

                // MARK: - Manual Generation
                Section {
                    Button {
                        Task { await generateDigestNow() }
                    } label: {
                        HStack {
                            Spacer()
                            if isGenerating {
                                ProgressView()
                                    .padding(.trailing, 8)
                                Text("Generating...")
                            } else {
                                Text("Generate Digest Now")
                            }
                            Spacer()
                        }
                    }
                    .disabled(isGenerating)
                } footer: {
                    if ghostwriterEnabled {
                        Text("Will trigger digest generation on the Ghostwriter server")
                    } else {
                        Text("Will generate a digest locally on this device")
                    }
                }
            }
            .navigationTitle("Settings")
            .task {
                await loadSettings()
            }
        }
    }

    // MARK: - Helper Methods

    private func periodColor(_ period: DigestPeriod) -> Color {
        switch period {
        case .morning: return .orange
        case .noon: return .yellow
        case .evening: return .purple
        }
    }

    private func loadSettings() async {
        do {
            enabledPeriods = try await settingsRepository.getEnabledPeriods()
            minWordCount = try await settingsRepository.getMinWordCount()
            showNotifications = try await settingsRepository.shouldShowNotifications()
            ghostwriterEnabled = try await settingsRepository.isGhostwriterEnabled()
        } catch {
            // Use defaults on error
        }
    }

    private func togglePeriod(_ period: DigestPeriod, enabled: Bool) async {
        do {
            try await settingsRepository.togglePeriod(period, enabled: enabled)
            enabledPeriods = try await settingsRepository.getEnabledPeriods()
        } catch {
            // Revert on error
        }
    }

    private func generateDigestNow() async {
        isGenerating = true
        defer { isGenerating = false }

        if ghostwriterEnabled {
            // Trigger on Ghostwriter server
            do {
                _ = try await ghostwriterCoordinator.triggerDigest(period: "manual")
                // Could poll for status here
            } catch {
                // Handle error
            }
        } else {
            // Local generation - would call DigestGenerator
            // For now just simulate
            try? await Task.sleep(nanoseconds: 2_000_000_000)
        }
    }
}
