//
//  SettingsView.swift
//  Epilogue
//
//  Created on 2026-01-26.
//  Copyright © 2026 Epilogue. All rights reserved.
//

import SwiftUI
import Domain
import GhostwriterClient

struct SettingsView: View {
    @Environment(\.settingsRepository) private var settingsRepository
    @EnvironmentObject private var ghostwriterCoordinator: GhostwriterSyncCoordinator
    @EnvironmentObject private var localDigestService: LocalDigestService

    @State private var apiKey = ""
    @State private var showApiKey = false
    @State private var enabledPeriods: Set<DigestPeriod> = [.morning]
    @State private var minWordCount = 300
    @State private var showNotifications = true
    @State private var ghostwriterEnabled = false
    @State private var isGenerating = false
    @State private var apiKeySaved = false
    @State private var ghostwriterStatus: DigestStatusResponse?
    @State private var ghostwriterStatusError: String?
    @State private var ghostwriterStatusTask: Task<Void, Never>?

    var body: some View {
        NavigationStack {
            Form {
                // MARK: - Ghostwriter Sync
                Section {
                    NavigationLink {
                        GhostwriterSettingsView(settingsRepository: settingsRepository)
                            .environmentObject(ghostwriterCoordinator)
                    } label: {
                        HStack {
                            Label("Ghostwriter", systemImage: "cloud.fill")
                            Spacer()
                            if ghostwriterEnabled {
                                Text("Enabled")
                                    .foregroundColor(.secondary)
                                    .font(.caption)
                            }
                            if ghostwriterCoordinator.isSyncing {
                                ProgressView()
                                    .scaleEffect(0.8)
                            } else if ghostwriterCoordinator.lastSyncError != nil {
                                Image(systemName: "exclamationmark.triangle.fill")
                                    .foregroundColor(.orange)
                            }
                        }
                    }
                } footer: {
                    if ghostwriterEnabled {
                        Text("Digests will be generated by the Ghostwriter server. Local generation is disabled.")
                    } else if let lastSync = ghostwriterCoordinator.lastSyncTime {
                        Text("Last sync: \(lastSync.formatted(date: .abbreviated, time: .shortened))")
                    }
                }

                // MARK: - API Configuration (only for local generation)
                if !ghostwriterEnabled {
                    Section("OpenAI API Key") {
                        HStack {
                            if showApiKey {
                                TextField("API Key", text: $apiKey)
                                    .textInputAutocapitalization(.never)
                                    .autocorrectionDisabled()
                            } else {
                                SecureField("API Key", text: $apiKey)
                                    .textInputAutocapitalization(.never)
                                    .autocorrectionDisabled()
                            }
                            Button {
                                showApiKey.toggle()
                            } label: {
                                Image(systemName: showApiKey ? "eye.slash" : "eye")
                                    .foregroundStyle(.secondary)
                            }
                            .buttonStyle(.borderless)
                        }
                        HStack {
                            Text("Required for Briefing mode. Get your key at platform.openai.com")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                            Spacer()
                            Button("Save") {
                                Task { await saveApiKey() }
                            }
                            .buttonStyle(.borderedProminent)
                            .controlSize(.small)
                        }
                    }
                    .alert("API Key Saved", isPresented: $apiKeySaved) {
                        Button("OK", role: .cancel) { }
                    }
                }

                // MARK: - Schedule
                Section {
                    ForEach(DigestPeriod.allCases, id: \.self) { period in
                        Toggle(isOn: Binding(
                            get: { enabledPeriods.contains(period) },
                            set: { enabled in
                                Task { await togglePeriod(period, enabled: enabled) }
                            }
                        )) {
                            HStack {
                                Image(systemName: period.iconName)
                                    .foregroundColor(periodColor(period))
                                    .frame(width: 24)
                                Text(period.displayName)
                                Spacer()
                                Text(period.displayTime)
                                    .foregroundColor(.secondary)
                            }
                        }
                    }
                } header: {
                    Text("Daily Schedule")
                } footer: {
                    if enabledPeriods.isEmpty {
                        Text("Select at least one time period")
                            .foregroundColor(.red)
                    } else if ghostwriterEnabled {
                        Text("Ghostwriter server will generate digests at selected times")
                    } else {
                        Text("EPUB will be generated locally at selected times")
                    }
                }

                // MARK: - Content Filters
                Section("Content Filters") {
                    VStack(alignment: .leading, spacing: 8) {
                        HStack {
                            Text("Minimum word count")
                            Spacer()
                            Text(minWordCount == 0 ? "Off" : "\(minWordCount)")
                                .foregroundStyle(.secondary)
                        }
                        Slider(
                            value: Binding(
                                get: { Double(minWordCount) },
                                set: { minWordCount = Int($0) }
                            ),
                            in: 0...1000,
                            step: 100
                        )
                    }
                    Text("Skip articles shorter than this (0 = include all)")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }

                // MARK: - Notifications
                Section("Notifications") {
                    Toggle("Show Digest Completion", isOn: $showNotifications)
                }

                // MARK: - Sync (only when Ghostwriter enabled)
                if ghostwriterEnabled {
                    Section {
                        Button {
                            Task { await syncNow() }
                        } label: {
                            HStack {
                                Label("Sync Now", systemImage: "arrow.triangle.2.circlepath")
                                Spacer()
                                if ghostwriterCoordinator.isSyncing {
                                    ProgressView()
                                }
                            }
                        }
                        .disabled(ghostwriterCoordinator.isSyncing)
                    } footer: {
                        if let error = ghostwriterCoordinator.lastSyncError {
                            Text("Sync error: \(error.localizedDescription)")
                                .foregroundColor(.red)
                        } else if let lastSync = ghostwriterCoordinator.lastSyncTime {
                            Text("Last sync: \(lastSync.formatted(date: .abbreviated, time: .shortened))")
                        }
                    }
                }

                // MARK: - Manual Generation
                Section {
                    Button {
                        Task { await generateDigestNow() }
                    } label: {
                        HStack {
                            Spacer()
                            if isGenerating || localDigestService.isGenerating {
                                ProgressView()
                                    .padding(.trailing, 8)
                                Text(localDigestService.generationStatus.isEmpty ? "Generating..." : localDigestService.generationStatus)
                            } else {
                                Text("Generate Digest Now")
                            }
                            Spacer()
                        }
                    }
                    .disabled(isGenerating || localDigestService.isGenerating || ghostwriterCoordinator.isSyncing)

                    if ghostwriterEnabled {
                        if let status = ghostwriterStatus {
                            VStack(alignment: .leading, spacing: 6) {
                                Text("Stage: \(status.stage ?? "starting")")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)

                                ProgressView(value: status.progress.progressPercentage)

                                Text("Feeds: \(status.progress.feedsFetched)/\(status.progress.totalFeeds) | " +
                                     "Articles: \(status.progress.articlesEnriched)/\(status.progress.totalArticles)")
                                    .font(.caption)
                                    .foregroundStyle(.secondary)
                            }
                            .padding(.top, 6)
                        }

                        if let error = ghostwriterStatusError {
                            Text("Error: \(error)")
                                .font(.caption)
                                .foregroundStyle(.red)
                        }
                    }
                } footer: {
                    if ghostwriterEnabled {
                        Text("Will trigger digest generation on the Ghostwriter server")
                    } else if let error = localDigestService.generationError {
                        Text("Last error: \(error.localizedDescription)")
                            .foregroundColor(.red)
                    } else if let digest = localDigestService.lastGeneratedDigest {
                        Text("Last digest: \(digest.articleCount) articles")
                    } else {
                        Text("Will generate a digest locally on this device")
                    }
                }
            }
            .navigationTitle("Settings")
            .task {
                await loadSettings()
            }
        }
    }

    // MARK: - Helper Methods

    private func periodColor(_ period: DigestPeriod) -> Color {
        switch period {
        case .morning: return .orange
        case .noon: return .yellow
        case .evening: return .purple
        }
    }

    private func loadSettings() async {
        do {
            apiKey = try await settingsRepository.getOpenAIKey() ?? ""
            enabledPeriods = try await settingsRepository.getEnabledPeriods()
            minWordCount = try await settingsRepository.getMinWordCount()
            showNotifications = try await settingsRepository.shouldShowNotifications()
            ghostwriterEnabled = try await settingsRepository.isGhostwriterEnabled()
        } catch {
            // Use defaults on error
        }
    }

    private func togglePeriod(_ period: DigestPeriod, enabled: Bool) async {
        do {
            try await settingsRepository.togglePeriod(period, enabled: enabled)
            enabledPeriods = try await settingsRepository.getEnabledPeriods()
        } catch {
            // Revert on error
        }
    }

    private func saveApiKey() async {
        do {
            try await settingsRepository.setOpenAIKey(apiKey)
            apiKeySaved = true
        } catch {
            // Handle error
        }
    }

    private func syncNow() async {
        await ghostwriterCoordinator.performFullSync()
    }

    private func generateDigestNow() async {
        if ghostwriterEnabled {
            // Trigger on Ghostwriter server
            isGenerating = true
            defer { isGenerating = false }
            do {
                ghostwriterStatusTask?.cancel()
                ghostwriterStatus = nil
                ghostwriterStatusError = nil

                let response = try await ghostwriterCoordinator.triggerDigest(period: "manual")
                guard let digestId = response.id else {
                    ghostwriterStatusError = "No digest ID returned"
                    return
                }

                ghostwriterStatusTask = Task {
                    await pollGhostwriterStatus(digestId: digestId)
                }
            } catch {
                ghostwriterStatusError = error.localizedDescription
            }
        } else {
            // Local generation
            await localDigestService.generateDigest()
        }
    }

    private func pollGhostwriterStatus(digestId: String) async {
        while !Task.isCancelled {
            do {
                let status = try await ghostwriterCoordinator.getDigestStatus(digestId: digestId)
                ghostwriterStatus = status

                if status.isComplete {
                    break
                }
            } catch {
                ghostwriterStatusError = error.localizedDescription
                break
            }

            try? await Task.sleep(nanoseconds: 1_500_000_000)
        }
    }
}
