package com.example.epilog.domain.model

/**
 * Indicates how a digest was triggered.
 */
enum class TriggerType {
    SCHEDULED,  // Generated by daily scheduled WorkManager job
    MANUAL      // Generated by user tapping "Run Now"
}
